### ISSUE TITLE
raise IOError(("MoviePy error: failed to read the duration of file %s.\n" OSError: MoviePy error: failed to read the duration of file

### ISSUE THREAD

**Issue by LouisLou2** [IcelandT/Bilibili-Parse#1]

**Comment by LouisLou2** [comment]
![error1](https://github.com/IcelandT/Bilibili-Parse/assets/113110433/5238ccaf-18b0-4c36-8ec0-d6af8011b9cb)
![error2](https://github.com/IcelandT/Bilibili-Parse/assets/113110433/4348055e-68ca-416b-87b1-671bbb35e2b1)
请问这个错误怎么避免啊

**Comment by IcelandT** [comment]
已经更新
